### PR TITLE
Convert db and web containers to use alpine images

### PR DESCRIPTION
**Pull request by tejasbubane**
Ref: #109, #92

### CODE REVIEW

**Comment by tejasbubane** [comment]
Not sure why the build fails. Am I missing something? cc @pichouk

**Comment by pichouk** [comment]
I think you should change the shebang on `web/docker-entry.sh` and `db/docker-entrypoint1.sh` to use `/bin/sh` instead of `/bin/bash` to be use in Alpine.

**Comment by tejasbubane** [comment]
@pichouk Still the same.

**Comment by pichouk** [comment]
It seems you have a syntax error on the `docker-entrypoint1.sh` file of database :
```
/docker-entrypoint1.sh: line 27: syntax error: unexpected "(" (expecting "fi")
```
This is because it use `sh` and not `bash`. I forgot that it could lead to syntax error, this file need to be refactor to work with `sh`.

**Comment by tejasbubane** [comment]
@pichouk I added `bash` package to alpine in order to keep it compatible with the script. I tried with `sh` and `ash`(which comes with alpine) but they don't see to support arrays which are used in the script. 

PS: `bash` is added only in db container, not in web since web works fine with `sh`.

**Comment by pichouk** [comment]
@tejasbubane Looks good to me if there is no other solution for now.
I will test the database container for few days on a production environment to  be sure we are safe with this :)

@xcompass I'll wait for your review/opinion on this PR before merging anyway :smile:

**Comment by xcompass** [comment]
@pichouk When you test the db container, could you test the WAL backup to S3 as well if possible? Thanks.

**Comment by pichouk** [comment]
@xcompass I never used AWS S3, I'll see if I could test this but I'm not sure.

@tejasbubane  I tried the database image on production and I run to the following issue :
```
AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
LOG:  invalid value for parameter "log_timezone": "localtime"
LOG:  invalid value for parameter "TimeZone": "localtime"
FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
```
I rollback because, you know, it is production :smile:. I will made some tests locally this week-end to (try to) figure out what's wrong.

I didn't test the Web container since my production infra use another reverse proxy (FYI [Traefik](https://traefik.io/)). I will test locally.

**Comment by pichouk** [comment]
@tejasbubane Did you manage to made the database container works on an existing Mattermost instance ?
I try to run this on my already setup server and I run to
```
FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
```

It works if I build a new server from scratch, but not with an existing one. I never add any modifications to my `postgresql.conf` file, it is the default one.

**Comment by haivala** [comment]
What's the situation with this?

**Comment by pichouk** [comment]
@haivala This is stale for now. If someone can found times to really tests this and be sure that it will not break anyone, we can then move on.

**Comment by mritd** [comment]
I think we should remove the `--no-cache` option when using the` apk add` or `apk update` command multiple times - because it avoids downloading the index file repeatedly and accelerates the build; 

Use `rm -rf /var/cache/apk/*` clear the index at the completion of the build; 

Compile tools should use `---virtual .build-deps`  to facilitate post-cleaning, like [nignx Dockerfile](https://github.com/nginxinc/docker-nginx/blob/1d2e2ccae2f6e478f628f4091d8a5c36a122a157/mainline/alpine/Dockerfile#L55)

**Comment by mritd** [comment]
The web dockerfile should avoid using the alpine tag without the version number; because it always points to the latest version of build; the docker will cache image, and the image with no version number thereafter will never be updated.

**Comment by pichouk** [comment]
Thanks @mritd for your suggestions.

I'm running out of time now to work on this, but I'll keep what you said in mind when we will go forward on Alpine version. If you want, you can also submit a PR based on the current one.

**Comment by pichouk** [comment]
Closing since we work on it with PR #208 #207 #198

**Pull request closed without merging**
