### PR TITLE
replace port 8000 to the default one and add gossip and stream ports

### PR DESCRIPTION
**Pull request by cpanato**
Replacing the 8000 to use the default port for Mattermost, with that we don't need to change the configuration and make it more standard with other apps

this was a question from Christopher and I already thought on that, and it makes sense to use the default one because in the host you can select any port.

cc
@pichouk @crspeller @jwilander

### CODE REVIEW

**Comment by pichouk** [comment]
LGTM but as we discussed with @jasonblais [the last time](https://pre-release.mattermost.com/core/pl/dpg79k7gyif8mxmoxg4tuafdah) we introduced a breaking change, we need to also inform users in the Mattermost official changelog (see [the previous example](https://docs.mattermost.com/administration/changelog.html#removed-and-deprecated-features)).

@cpanato are you able to push a message to the Mattermost `5.4` changelog or is it too late ?

**Comment by cpanato** [comment]
we can merge it for 5.5 and make the announcement on 5.5

**Comment by pichouk** [comment]
Ok, I'll upgrade the repository to `5.4.0` in few minutes.

I keep this PR for `5.5` and we will make all announcement we need prior the `5.5` release :)

**Comment by cpanato** [comment]
sure @pichouk i will post in the docker channel as well

**Comment by cpanato** [comment]
ok @pichouk updated the readme for `5.5.0` 

@jasonblais can we include a note in the release notes for the docker image? similar to this one? https://github.com/mattermost/docs/pull/1945/files

**Comment by jasonblais** [comment]
We can add a note for 5.5. 

Why are we making the breaking change? Could we have timed it with a major version release (e.g. v6.0)

**Comment by cpanato** [comment]
Discussed with @jasonblais in pre-release.
We will hold this change until we release version 6.0.0

**Comment by crspeller** [comment]
Going to close this because we have no idea when 6.0 will happen. @cpanato Can you make sure there is a 6.0 ticket that links to this PR?

**Comment by jasonblais** [comment]
Created a ticket here with a note on v6.0 release https://mattermost.atlassian.net/browse/MM-13614

**Pull request closed without merging**
