### PR TITLE
Allow config location to be customized from CLI

### PR DESCRIPTION
**Pull request by xcompass**
Config file should be stored in a persistent storage as it is stores the
app status and configuration. It should be independent from container
life cycle and mounted into app container. This commit allows config
location to be changed through CLI. So that when the persistent storage
is mounted, the location can be pointed to the mounted config file.

Also some updates for best practices:
* extracted version numbers in Dockerfile into a environment variable
* Added mattermost/bin to PATH environment variable

### CODE REVIEW

**Comment by npcode** [comment]
Could you please update this to resolve the conflict?

**Comment by xcompass** [comment]
@npcode done.

**Comment by jasonblais** [comment]
Hey @xcompass, thank you for your contributions to the `mattermost-docker` repo!

Wondering if you'd be interested joining the [Mattermost community instance](https://pre-release.mattermost.com/core/channels/installers-and-images) and meeting other contributors?

Would be nice to discuss potential next steps on the docker repo and have you involved in the conversation, given your active involvement here.

**Comment by xcompass** [comment]
@jasonblais thanks. Joined

**Comment by xcompass** [comment]
@jasonblais @npcode could one of you review my PR? Thanks.

**Comment by jasonblais** [comment]
I don't have the technical knowledge to review it, maybe @npcode can help?

**Comment by npcode** [comment]
I think it would be better if the usage is documented in README.md.

**Comment by xcompass** [comment]
@npcode Thanks. I've updated the readme to describe the environment variables.

**Comment by npcode** [comment]
@xcompass Thanks for the nice documentation. Now it looks good to me.

**Pull request merged**
