### PR TITLE
Do you want any help ?

### PR DESCRIPTION
**Pull request by pichouk**
Hi @xcompass !
If you're interesting in some help to maintain this project, I'll be happy to participate.

### CODE REVIEW

**Comment by xcompass** [comment]
That's great! Thanks for the offer

**Comment by jasonblais** [comment]
Thanks @pichouk for the offer! Really appreciated. I will ask one of our team members to give you permissions for the repository.

I'll also add your name as one of the core developers on the Docker repo: https://docs.mattermost.com/developer/core-developer-handbook.html#current-core-developers

**Comment by jasonblais** [comment]
@pichouk If you're interested, you're welcome to join our community site at https://pre-release.mattermost.com/core

Would love to say "hi" and keep you in touch with the rest of the community and the Mattermost staff.

**Comment by pichouk** [comment]
Thank you !
I'll join you for sure :)

**Pull request merged**
