### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wiersgallak**
Update README with a context of the status of this repo & a link to new repo.

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
maybe we can add a big alert icon to people get the attention

**Comment by wiersgallak** [comment]
@cpanato I am not sure how exactly to add something to make it have more attention.  Any suggestions? Can I just add a image? Also are you able to merge?  It appears I don't have access.

**Comment by cpanato** [comment]
@wiersgallak 

something like this

```
|![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Warning.svg/156px-Warning.svg.png) | This project is no longer supported.
|---|---|
```

| | This project is no longer supported.
|---|---|

**Comment by wiersgallak** [comment]
Thanks @cpanato!  Added.  I think we should be good to merge then.

**Pull request merged**
