### PR TITLE
allow uncommenting for team edition

### PR DESCRIPTION
**Pull request by igor47**
currently, if you follow the instructions and uncomment the lines, you
will get a YAML error:

```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 23, column 5
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 25, column 7
```

found the potential solution in mattermost/mattermost-docker#343

### CODE REVIEW

**Comment by cpanato** [comment]
@igor47 please sign the CLA when you have a chance

**Comment by igor47** [comment]
signed

**Comment by jasonblais** [comment]
@cpanato quick reminder to help with review, thanks! :)

**Comment by cpanato** [comment]
@igor47 please update your PR and resolve the conflicts

**Comment by cpanato** [comment]
@igor47 can you please update your PR and resolve the conflict? thanks!

**Comment by jasonblais** [comment]
> @igor47 can you please update your PR and resolve the conflict? thanks!

@cpanato is this something we can help with? This contribution includes a small change to the docker-compose file

**Comment by igor47** [comment]
rebased. it might no longer be necessary since #438 so feel free to close.

**Comment by jasonblais** [comment]
Thank you @igor47! @cpanato please help review

**Pull request merged**
