### PR TITLE
Update docker-compose file to v2 format

### PR DESCRIPTION
**Pull request by Andrey9kin**

### CODE REVIEW

**Comment by Andrey9kin** [comment]
@npcode could you please take a look?

**Comment by npcode** [comment]
Thanks @Andrey9kin for the pull request!

Per the CONTRIBUTING.md file displayed when you created this pull request, we need to add you to the list of approved contributors for the Mattermost project.

Please help complete the Mattermost contribution license agreement?

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.

Please let us know if you have any questions.

We are very happy to have you join our growing community!

**Comment by npcode** [comment]
Thanks @Andrey9kin for the pull request!

Per the CONTRIBUTING.md file displayed when you created this pull request, we need to add you to the list of approved contributors for the Mattermost project.

Please help complete the Mattermost contribution license agreement?

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.

Please let us know if you have any questions.

We are very happy to have you join our growing community!

**Comment by npcode** [comment]
I'll take a look on Monday because i'm on vacation. Thanks!

**Comment by npcode** [comment]
Sorry, @Andrey9kin. I omitted the link to the contribution license agreement.

Could you please complete the agreement?

**Comment by Andrey9kin** [comment]
@npcode I just signed contribution license agreement. How long does it take to add me to the list of approved contributors?

**Comment by xcompass** [comment]
Hi @Andrey9kin, I saw you are already on the list. My only concern is for those who are still on v1 and can't upgrade yet. Since this will be a breaking change for them. Could we keep the original compose file and rename it to something like docker-compose-v1.yml?

**Comment by Andrey9kin** [comment]
@xcompass I added v1 compose file as requested

**Pull request merged**
