### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by ngpestelos**
Wait for the`db` service to finish before starting the`app` service.

### CODE REVIEW

**Comment by xcompass** [comment]
@ngpestelos could you rebase it. I think it will fix the failed tests.

**Comment by xcompass** [comment]
Thanks @ngpestelos for the pull request!

 Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.

Please let us know if you have any questions.

We are very happy to have you join our growing community!

**Comment by nikosch86** [comment]
@ngpestelos `depends_on` will not wait for the service to do anything, as of the current docker-compose version it will only wait for the container to come up, which is not the same state as the database being ready  
a script like `wait-for-it` should be used for that, https://github.com/nikosch86/wait-for-it

**Comment by xcompass** [comment]
I'm closing this in favor of https://github.com/mattermost/mattermost-docker/pull/99

**Pull request closed without merging**
