### PR TITLE
add TLS 1.3 support to web container

### PR DESCRIPTION
**Pull request by nvjacobo**
#### Summary

Add TLS 1.3 support to nginx web server. 

Thanks, Jacobo

### CODE REVIEW

**Comment by enahum** [comment]
FYI iOS mobile app currently does not support connecting the WebSocket with TLS 1.3

**Comment by nvjacobo** [comment]
> FYI iOS mobile app currently does not support connecting the WebSocket with TLS 1.3

Thanks for your feedback @enahum!

 It seems that iOS mobile app can use the older versions. Support for older versions is not removed.

**Comment by enahum** [comment]
@nvjacobo maybe listed as a known issue in the readme?

**Comment by nvjacobo** [comment]
> @nvjacobo maybe listed as a known issue in the readme?

This change has TLSv1 TLSv1.1 TLSv1.2 TLSv1.3 for chose by client. 

I am reading apple documents (https://developer.apple.com/security/) It seems iOS has support 1.2.

**Comment by enahum** [comment]
IOS does support it, but the WebSocket implementation that we have does not. I know this for a fact as I’ve been running tests for a new implementation because of this issue

**Comment by enahum** [comment]
As long as TLS 1.1 or 1.2 are also enabled, it should be ok

**Pull request merged**
