### PR TITLE
Update link to install guide

### PR DESCRIPTION
**Pull request by jasonblais**
Addresses #84

### CODE REVIEW

**Comment by jasonblais** [comment]
@xcompass Comes to mind - I'm not sure if we want to have references to our other install guides?

We currently have four separate guides

image

**Comment by xcompass** [comment]
@jasonblais How about adding a link I add a link to the above page in the readme in case someone is not using docker?

**Comment by jasonblais** [comment]
Yeah, that would work. The link to that page is: https://docs.mattermost.com/guides/administrator.html#installing-mattermost

**Comment by xcompass** [comment]
Thanks. Done.

**Pull request merged**
