### PR TITLE
update readme to add deprecation notice

### PR DESCRIPTION
**Pull request by cpanato**
Jira: https://mattermost.atlassian.net/browse/MM-15327

### CODE REVIEW

**Comment by cpanato** [comment]
can you take a look @jasonblais  thanks!

**Comment by jasonblais** [comment]
@cpanato Is this how the texts at https://hub.docker.com/u/mattermost are generated by?

**Comment by cpanato** [comment]
in docker hub they have a limited text field so the entire message was not possible.
the site show the readme from the repo, so this message will appears here : https://hub.docker.com/r/mattermost/mattermost-prod-app

**Comment by jasonblais** [comment]
@cpanato I was primarily looking to update the descriptions/texts that appear on the home page here https://hub.docker.com/u/mattermost

I'm a bit worried we now have a big warning at the top of the README file which makes it look like this repo is no longer maintained.

image

**Comment by jasonblais** [comment]
@cpanato @pichouk To add, I'd propose reverting and moving this as a bullet in the "Notes" section.

If we need a shorter text for what's displayed in the description at https://hub.docker.com/u/mattermost, I can provide you one. Just let me know the approximate max character count for the description field.

**Comment by pichouk** [comment]
Sorry I merged too quick. I opened a PR to revert : https://github.com/mattermost/mattermost-docker/pull/389

**Pull request merged**
