### PR TITLE
fix typo in readme

### PR DESCRIPTION
**Pull request by adam-golab**
I fixed one small typo in readme
Ent**re**prise => Ent**er**prise

### CODE REVIEW

**Comment by adam-golab** [comment]
I don't want to provide all of my personal information like mailing address, phone number or Skype ID to fix only one typo in the readme. So if my personal data are necessary then please close this issue.

**Comment by pichouk** [comment]
Understandable :)
I don't know how strong is the CLA policy for Mattermost (@jasonblais ?), I'll do the commit to fix the typo. Anyway, thanks for the report :)

**Comment by pichouk** [comment]
Understandable :)
I don't know how strong is the CLA policy for Mattermost (@jasonblais ?), I'll do the commit to fix the typo. Anyway, thanks for the report :)

**Comment by jasonblais** [comment]
@pichouk Generally all Mattermost contributions should have CLA signed :) 

Thank you @adam-golab for the feedback though, will take it into consideration. If we were asking for your name, email and GitHub username, would you have been more open to signing the agreement?

**Comment by adam-golab** [comment]
@jasonblais only name, email and GitHub username sound a lot better :)

Still, to be honest, I don't think that providing any additional data is necessary (you can get this information from commit data).  It's hard to contribute, open PR with some reasonable changes by mistake. There is a description of contribution rules in `MAINTENANCE.md` file, there may be Code of Conduct described in another file.
So, for me, opening a PR means that you are familiar and agree with those rules.

**Pull request closed without merging**
