### PR TITLE
Update Dockerfile to v5.31.0

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Comment by amyblais** [comment]
@metanerd FYI

**Comment by metanerd** [comment]
Can we do this automatic this time with the bot?

**Comment by amyblais** [comment]
@metanerd Yes please. Not sure what the bot is

**Comment by metanerd** [comment]
As soon as we cut the release branches, it will also create this PR here. If that timing isn't right, then I should probably move it to directly after a release.

**Comment by amyblais** [comment]
@metanerd It may a little different each month since on-prem releases are now based off cloud releases, but in this case we can probably use this PR because v5.32 branch won't be cut until Jan 26th (v5.32 will be based off Jan 26th cloud release).

**Review by metanerd — APPROVED** [review]

**Comment by amyblais** [comment]
@metanerd Thanks, I don't have merge permissions here.

**Comment by maxraab** [comment]
Could you also tag the new version automatically after merging?

**Comment by amyblais** [comment]
> Could you also tag the new version automatically after merging?

FYI @metanerd

**Comment by metanerd** [comment]
Tag is created. 

@amyblais Please ping me before you would create this PR next release.

**Comment by amyblais** [comment]
Sounds good! Thanks!

**Pull request merged**
