### PR TITLE
Upgrade alpine to 3.9

### LINKED ISSUE #360: Upgrade to Alpine 3.9
The issue with `xmlsec-openssl` should be fixed in Alpine 3.9:
https://github.com/mattermost/mattermost-docker/issues/309
https://bugs.alpinelinux.org/issues/9110
https://github.com/alpinelinux/aports/commit/cb878459e4c26088bf0eee4837cc39171b1cec87

So please consider upgrading to Alpine 3.9.

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #360

### CODE REVIEW

**Comment by cpanato** [comment]
thanks for this PR @tejasbubane before merging it I will test if one dependency we use works on this new alpine

**Comment by hanzei** [comment]
Hey @cpanato,

Gently reminder about testing this :wink:

**Comment by cpanato** [comment]
tested in community-daily and the xmlsec is working as expected. thanks and sorry for the delay

**Pull request merged**
