### PR TITLE
Fix Dockerrun.aws.json so that it works with the latest docker setup

### PR DESCRIPTION
**Pull request by mkdbns**
The current Dockerrun.aws.json is about a year old and no longer works. I believe I've fixed the issues and would like to have this committed to the repo.

### CODE REVIEW

**Comment by pichouk** [comment]
Hi @mkdbns 
I'm sorry I merged but I forgot to ask you to sign the contribution license agrement. Here is the message I should send to you normally :

Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.

Please let us know if you have any questions.

We are very happy to have you join our growing community!

Let me now once you signed (or not if you don't want to). Thanks for the contribution.

**Comment by hmhealey** [comment]
Thanks for signing that, @mkdbns

I've configured Mattermod to check for CLAs here now, @pichouk, so it'll be posted automatically :)

**Comment by pichouk** [comment]
I don't know what happen but the commit which change the default version to `team` was not present when I merged (you can see it was not applied on master).
@mkdbns did you push force or something ? Don't understand what happen.

**Comment by mkdbns** [comment]
I cannot seem to respond to the comment directly in Github so replying to
the email. Originally, I had made a 1 line change to make "team" the
default version as I was debugging why the AWS deploy didn't work. I ended
up reverting the change in the following commit - to maintain enterprise as
the default. Thus, the only change that should be visible in the merge is
the Dockerrun.aws.json file.


*Michael DeBonis*
Founder + CEO
mike@devised.io  •  512.695.4087  •  www.devised.io

**Comment by pichouk** [comment]
Thanks for answer and for signing. And thanks again for your contribution ;)

**Pull request merged**
