### PR TITLE
DOPS-215: Add MM_INSTALL_TYPE=docker environment variable.

### PR DESCRIPTION
**Pull request by metanerd**
#### Summary
Sets an environment variable to get an idea of the preferred installation type.  

#### Ticket Link

https://mattermost.atlassian.net/browse/DOPS-215

### CODE REVIEW

**Comment by cpanato** [comment]
after this gets merged can you cherry pick to branches `5.26`/ `5.27` ? thanks!

**Comment by cpanato** [comment]
did you validate when you start the docker container if this env is set there? @metanerd

**Comment by metanerd** [comment]
@cpanato 

I did not, but it looks good: 
```
$ docker exec -it mattermost-docker_app_1 sh
~ $ printenv
MM_PASSWORD=mmuser_password
MM_VERSION=5.27.0
HOSTNAME=e126a4458346
SHLVL=1
HOME=/mattermost
MM_INSTALL_TYPE=docker
...
```

**Review by cpanato — APPROVED** [review]
thanks!

**Pull request merged**
